### ISSUE TITLE
Update people and authors

### ISSUE THREAD

**Issue by dsevero** [3778/website-research#1]
- [x] @rgiglio 
- [x] @lrleo 
- [x] @renatocmaciel 
- [x] @saulodspedro 
- [x] @marciogregory 
- [x] @GabrielSimonetto 

Please provide me with the following. Go ahead and comment it in this thread.

```
---
# Display name
name: Daniel Severo
role: Machine Learning Researcher
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"
social:
- icon: twitter
  icon_pack: fab
  link: https://twitter.com/_dsevero
- icon: github
  icon_pack: fab
  link: https://github.com/dsevero
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/danielsevero
---
```

**Comment by GabrielSimonetto** [comment]
```
---
# Display name
name: Gabriel Simonetto
role: Intern
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"

social:
- icon: github
  icon_pack: fab
  link: https://github.com/GabrielSimonetto/
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/gabriel-simonetto/
---
```

**Comment by rgiglio** [comment]
```
---
# Display name
name: Ricardo Giglio
role: Researcher
organizations:
- name: UFSC
  url: "https://www.ufsc.br"
- name: 3778 Healthcare
  url: "https://www.3778.care"
social:
- icon: twitter
  icon_pack: fab
  link: https://twitter.com/ricagiglio
- icon: github
  icon_pack: fab
  link: https://github.com/rgiglio
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/ricardogiglio
---
```

**Comment by leoramme** [comment]
```
---
# Display name
name: Leonardo Rammé
role: Machine Learning Engineer (Intern)
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"

social:
- icon: github
  icon_pack: fab
  link: https://github.com/lrleo
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/leonardoramme/
---
```

**Comment by marciogregory** [comment]
```
---
# Display name
name: Marcio Gregory
role: Machine Learning Researcher
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"
social:
- icon: github
  icon_pack: fab
  link: https://github.com/marciogregory
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/marcio-gregory
---
```

**Comment by saulodspedro** [comment]
```
---
# Display name
name: Saulo Pedro
role: Machine Learning Researcher
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"
social:
- icon: github
  icon_pack: fab
  link: https://github.com/saulodspedro
- icon: linkedin
  icon_pack: fab
  link: www.linkedin.com/in/saulo-pedro
- icon: googlescholar
  icon_pack: fab
  link: https://scholar.google.com/citations?user=Kz0xxhoAAAAJ
---
```

**Comment by renatocmaciel** [comment]
```
---
# Display name
name: Renato Maciel
role: Data Scientist
organizations:
- name: 3778 Healthcare
  url: "https://www.3778.care"
social:
- icon: github
  icon_pack: fab
  link: https://github.com/renatocmaciel
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/renato--maciel/
---
```
